[project]
name = "deps-python-example"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "paho-mqtt>=1.5.1",
    "asyncio>=3.4.3",
    "protobuf>=6.32.1",
    "mypy-protobuf>=3.6.0",
    "deps @ git+https://github.com/grida-energy/deps.git@v0.0.1c",
    "python-dotenv>=1.1.1",
]
